### PR TITLE
Ensure context lines option is used (fixes #740)

### LINKED ISSUE #740: context_lines setting is never used
I was attempting to limit the lines of context by setting `context_lines => 1`, but it looks like it's hard coded for 5 lines of pre and post context: https://github.com/getsentry/sentry-php/blob/master/src/Stacktrace.php#L134

### PR DESCRIPTION
**Pull request by mattzuba**
Tests included, ensures that the context options that are set are used, rather than being hard-coded to a constant.

### CODE REVIEW

**Comment by mattzuba** [comment]
Looks like the get/setContextLines methods allow for possible null, but the OptionsResolver only allows an int, do you mind if I change the method signatures of these to be int only?

**Comment by ste93cry** [comment]
>Looks like the get/setContextLines methods allow for possible null, but the OptionsResolver only allows an int

That's indeed another bug and I agree that the parameter should not be `nullable`. Maybe we can also optimize a bit the code in `Stacktrace::getSourceCodeExcerpt()` by checking if `$maxLinesToFetch` is greater than 0 and if not return early instead of opening the file anyway to read nothing. There is also another bug I'm seeing right now that is being reported by Scrutinizer: we're calling that method as if it was a `static` one but it's not

https://github.com/getsentry/sentry-php/blob/5ec1fbec3ff7c32dda49f234a2d5db5759393676/src/Stacktrace.php#L134

**Comment by mattzuba** [comment]
Even if `$maxLinesToFetch` was 0, you'd still want to open the file to read the line that was a part of the stack though, right?

File: src/Options.php [hunk 1]
```diff
@@ -616,7 +616,7 @@ private function configureOptions(OptionsResolver $resolver): void
             'sample_rate' => 1,
             'mb_detect_order' => null,
             'attach_stacktrace' => false,
-            'context_lines' => 3,
+            'context_lines' => 5,
```
Comment (Jean85) [inline src/Options.php]: @HazAT which should be the right default for this value? Which is the "normal" default on the server side?

File: tests/StacktraceTest.php [hunk 2]
```diff
@@ -188,6 +188,34 @@ public function testAddFrameReadsCodeFromLongFile(): void
         }
     }
 
+    public function testAddFrameUsesOptionsContext(): void
+    {
+        $this->options->setContextLines(2);
```
Comment (Jean85) [inline tests/StacktraceTest.php]: Can you add a data provider to this test so we can see it work with `0` and two other different values?

**Comment by ste93cry** [comment]
>Even if $maxLinesToFetch was 0, you'd still want to open the file to read the line that was a part of the stack though, right?

As a user I would expect no lines to be sent to Sentry if the value of that option is set to 0. I may be wrong but I think that actually the number of lines also includes the line that originated the frame itself

**Comment by HazAT** [comment]
Setting it to `0` should just remove the `pre` and `post` context lines, the line of the frame in the stacktrace should still be there.
btw thanks for the work 👍

**Comment by mattzuba** [comment]
I didn't forget about this guys, just been busy at work.  I'll try to get a data provider setup on the test and merge the other test and update the PR today or tomorrow.

**Comment by ste93cry** [comment]
@mattzuba are you willing to make the requested changes? We would like to release `beta 2` asap and it would be cool if this bugfix was part of that version

File: tests/StacktraceTest.php (hunk 2 above)
Comment (mattzuba) [reply tests/StacktraceTest.php]: Please review the latest changes - I moved the redunant tests that @ste93cry mentioned into the dataprovider and created a few additional ones (zero context, context near end and beginning of file).

File: tests/StacktraceTest.php [hunk 3]
```diff
@@ -138,54 +138,47 @@ public function testAddFrameMarksAsInApp(): void
         $this->assertTrue($frames[1]->isInApp());
     }
 
-    public function testAddFrameReadsCodeFromShortFile(): void
+    /**
+     * @dataProvider contextDataProvider
+     */
+    public function testAddFrameWithDifferentContexts($fixture, $lineNumber, $contextLines, $preContextCount, $postContextCount)
```
Comment (ste93cry) [inline tests/StacktraceTest.php]: Please rename this test method to `testAddFrameRespectsContextLinesOption`

File: tests/StacktraceTest.php [hunk 4]
```diff
@@ -138,54 +138,47 @@ public function testAddFrameMarksAsInApp(): void
...
 
-        for ($i = 0; $i < 2; ++$i) {
-            $this->assertEquals(rtrim($fileContent[$i + 3]), $frames[0]->getPostContext()[$i]);
+        for ($i = 0; $i < $postContextCount; ++$i) {
+            $this->assertEquals(rtrim($fileContent[$i + $lineNumber]), $frames[0]->getPostContext()[$i]);
         }
     }
 
-    public function testAddFrameReadsCodeFromLongFile(): void
+    public function contextDataProvider()
```
Comment (ste93cry) [inline tests/StacktraceTest.php]: As a convention used across the codebase we used for the name of the method of the data provider the name of the test method that uses it + the `DataProvider` suffix. The only exception is if the data provider is used from more than one test method

File: tests/StacktraceTest.php (hunk 2 above)
Comment (ste93cry) [reply tests/StacktraceTest.php]: Still some more minor fixes, the rest looks good!

File: tests/StacktraceTest.php (hunk 3 above)
[the remark this answers is not in the document]
Comment (mattzuba) [reply tests/StacktraceTest.php]: Added these to parameters and also added return types

File: tests/StacktraceTest.php [hunk 5]
```diff
@@ -138,54 +138,47 @@ public function testAddFrameMarksAsInApp(): void
...
     }
 
-    public function testAddFrameReadsCodeFromShortFile(): void
+    /**
+     * @dataProvider contextDataProvider
+     */
+    public function testAddFrameWithDifferentContexts($fixture, $lineNumber, $contextLines, $preContextCount, $postContextCount)
     {
-        $fileContent = explode("\n", $this->getFixture('code/ShortFile.php'));
+        if (isset($contextLines)) {
```
[the remark this answers is not in the document]
Comment (mattzuba) [reply tests/StacktraceTest.php]: Done

File: tests/StacktraceTest.php (hunk 3 above)
Comment (mattzuba) [reply tests/StacktraceTest.php]: Done

File: tests/StacktraceTest.php (hunk 4 above)
Comment (mattzuba) [reply tests/StacktraceTest.php]: Done

**Comment by mattzuba** [comment]
Made the requested changes and rebased against master as well.
