### PR TITLE
#901: Replace critical with fatal status

### LINKED ISSUE #901: Invalid breadcrumb level
Based on your [documentation](https://docs.sentry.io/enriching-error-data/breadcrumbs/?platform=php) breadcrumbs support the level `debug`, `info`, `warning`, `error` and `fatal` (see screenshot).

image

But the Breadcrumb class has a constant with the value `critical`, which is part of the allowed levels arrey, which is also used for validation in the constructor ([Breadcrumb.php#L64](https://github.com/getsentry/sentry-php/blob/be044bfa83ff98c5dd0ea0a7ff243ff0eade721c/src/Breadcrumb.php#L64)).

This issue causes confusion and conflict when translating PSR3 log levels to sentry breadcrumb levels. In addition neither the level `critical` nor the level `fatal` have special highlighting on a sentry exception. Only `warning` and `error` status receive a meaningful styling.

Please clearify which is now correct, `critical` or `fatal`. Either way please update the documentation and/or the php sdk. If `fatal` is the correct one, I would suggest adding the correct constant and deprecating the critical one.

### PR DESCRIPTION
**Pull request by TheLevti**
Critical breadcrumb status is not supported. Replaced it with fatal.

Fixes #901

### CODE REVIEW

File: src/Breadcrumb.php [hunk 1]
```diff
@@ -59,9 +59,9 @@ final class Breadcrumb implements \JsonSerializable
     public const LEVEL_ERROR = 'error';
 
     /**
-     * This constant defines the critical level for a breadcrumb.
+     * This constant defines the fatal level for a breadcrumb.
      */
-    public const LEVEL_CRITICAL = 'critical';
```
Comment (ste93cry) [inline src/Breadcrumb.php]: Thank you for the contribution. However, this is a breaking change as the constant is `public` and may be used by someone. Please add a new constant that defines the correct value and mark as deprecated this one

Comment (TheLevti) [reply src/Breadcrumb.php]: Thanks, will do that.

Comment (TheLevti) [reply src/Breadcrumb.php]: Should the deprecated constant be still in the allowed array?

Comment (ste93cry) [reply src/Breadcrumb.php]: Yes, if we don't allow the value anymore we would possibly still break existing applications

Comment (TheLevti) [reply src/Breadcrumb.php]: Done.

File: src/Breadcrumb.php [hunk 2]
```diff
@@ -60,9 +60,16 @@ final class Breadcrumb implements \JsonSerializable
 
     /**
      * This constant defines the critical level for a breadcrumb.
+     *
+     * @deprecated 2.2.2 Use fatal instead. Will be removed in a later version.
```
Comment (ste93cry) [inline src/Breadcrumb.php]: Please change this description to `@deprecated since version 2.2.2, to be removed in 3.0` so that it's consistent with the rest of the code

Comment (Jean85) [inline src/Breadcrumb.php]:
```suggestion
     * @deprecated since version 2.2.2, to be removed in 3.0; use fatal instead.
```

**Comment by Jean85** [comment]
Also, please add an entry to the changelog.

Thank you for spotting and fixing this!
