### PR TITLE
fix: Do not throw an TypeError on numeric HTTP headers

### LINKED ISSUE #1369: Error in RequestIntegration when HTTP header name is numeric
### How do you use Sentry?

Self-hosted/on-premise

### Version

3.2.0

### Steps to Reproduce

- Use latest `sentry-laravel` @ 2.13.0.
- Send a query that use a numeric HTTP header such as `curl -v -H "123: test" https://www.example.com`
- Notice an error in PHP error log (see below).

### Expected Result

No error is produced in PHP error log.

### Actual Result

From PHP error log:
```
PHP Fatal error:  Uncaught TypeError: strtolower(): Argument #1 ($string) must be of type string, int given in /data/site/vendor/sentry/sentry/src/Integration/RequestIntegration.php:179
Stack trace:
#0 /data/site/vendor/sentry/sentry/src/Integration/RequestIntegration.php(179): strtolower(1)
#1 /data/site/vendor/sentry/sentry/src/Integration/RequestIntegration.php(157): Sentry\Integration\RequestIntegration->sanitizeHeaders(Array)
#2 /data/site/vendor/sentry/sentry/src/Integration/RequestIntegration.php(115): Sentry\Integration\RequestIntegration->processEvent(Object(Sentry\Event), Object(Sentry\Options))
#3 /data/site/vendor/sentry/sentry/src/State/Scope.php(370): Sentry\Integration\RequestIntegration->Sentry\Integration\{closure}(Object(Sentry\Event), Object(Sentry\EventHint))
#4 /data/site/vendor/sentry/sentry/src/Client.php(264): Sentry\State\Scope->applyToEvent(Object(Sentry\Event), Object(Sentry\EventHint))
#5 /data/site/vendor/sentry/sentry/src/Client.php(147): Sentry\Client->prepareEvent(Object(Sentry\Event), Object(Sentry\EventHint), Object(Sentry\State\Scope))
#6 /data/site/vendor/sentry/sentry/src/Client.php(139): Sentry\Client->captureEvent(Object(Sentry\Event), Object(Sentry\EventHint), Object(Sentry\State\Scope))
#7 /data/site/vendor/sentry/sentry/src/State/Hub.php(138): Sentry\Client->captureException(Object(TypeError), Object(Sentry\State\Scope), Object(Sentry\EventHint))
#8 /data/site/app/Exceptions/Handler.php(151): Sentry\State\Hub->captureException(Object(TypeError))
#9 /data/site/app/Exceptions/Handler.php(87): App\Exceptions\Handler->reportWithSentry(Object(TypeError))
#10 /data/site/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(191): App\Exceptions\Handler->report(Object(TypeError))
#11 /data/site/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(259): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(TypeError))
#12 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(Object(TypeError))
#13 {main}
  thrown in /data/site/vendor/sentry/sentry/src/Integration/RequestIntegration.php on line 179
```

### PR DESCRIPTION
**Pull request by cleptric**
Fixes #1369 

While I'm not entirely sure if numeric headers are in sync with the spec, we should definitely not throw an `TypeError` in this case.

### CODE REVIEW

File: src/Integration/RequestIntegration.php [hunk 1]
```diff
@@ -169,13 +169,16 @@ private function processEvent(Event $event, Options $options): void
     /**
      * Removes headers containing potential PII.
      *
-     * @param array<string, string[]> $headers Array containing request headers
+     * @param array<mixed, string[]> $headers Array containing request headers
```
Comment (Jean85) [inline src/Integration/RequestIntegration.php:172]: You could either do
```suggestion
     * @param array<array-key, string[]> $headers Array containing request headers
```
or 
```suggestion
     * @param string[] $headers Array containing request headers
```

**Review by Jean85 — CHANGES_REQUESTED** [review]
PHP implicitly converts integer strings to integers when using it for array keys, that's the key of the issue.

Fixing the PHPDoc would make the issue surface at the static analysis level.

File: src/Integration/RequestIntegration.php (hunk 1 above)
Comment (cleptric) [reply src/Integration/RequestIntegration.php]: I'm not sure what you mean by "surface at the static analysis level", but I do like using `array-key` allows me to drop the added entry to the baseline file.

Comment (Jean85) [reply src/Integration/RequestIntegration.php]: I meant exactly that :smile: if it was in the baseline, the static analysis was already picking this bug, it was just silenced.

**Review by Jean85 — APPROVED** [review]

**Review by stayallive — APPROVED** [review]
