### PR TITLE
Treat the project ID component of the DSN as a `string` rather than an `integer`

### LINKED ISSUE #1292: Project IDs should be strings
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) or self-hosted/on-premise (which version?)

Which SDK and version?
PHP

### Steps to Reproduce

https://github.com/getsentry/sentry-php/blob/ea704bbe145657a507d73cd8bf6cc017d269fffa/src/Dsn.php#L102

### Expected Result

Project IDs should be cast as strings, not int

### Actual Result

Project IDs are int in from PHP sdks

we need project ID to not be forced to an integer because its plausible we will need it to be a UUID, or we will need it to be a 64 bit int (which breaks in JS, as an example)

### PR DESCRIPTION
**Pull request by ste93cry**
Fixes #1292. With this PR, the `Dsn::getProjectId()` method deprecates returning the project ID as an `integer`. In the next major version, we can reintroduce the return type and make it `string`. It looks like version `2.x` was correct, but this behaviour was lost when we introduced the `Dsn` class. I'm unsure whether we want to classify this as a bug or as a feature. In any case, we cannot avoid the code to handle both typehints as changing it would be a breaking change

### CODE REVIEW

**Review by Jean85 — APPROVED** [review]

File: src/Dsn.php [hunk 1]
```diff
@@ -99,7 +99,7 @@ public static function createFromString(string $value): self
         $segmentPaths = explode('/', $parsedDsn['path']);
         $projectId = array_pop($segmentPaths);
 
-        if ((int) $projectId <= 0) {
+        if (!ctype_digit($projectId)) {
```
Comment (stayallive) [inline src/Dsn.php:102]: This will still fail if the project ID is a non-number, so project ID cannot be a UUID for example with this change still.

Shouldn't we move this check to the getter when returning `int` because returning a non-number as `int` could cause unexpected results (which is probably why this check is still here)?

**Review by stayallive — CHANGES_REQUESTED** [review]

File: src/Dsn.php (hunk 1 above)
Comment (ste93cry) [reply src/Dsn.php:102]: >This will still fail if the project ID is a non-number, so project ID cannot be a UUID for example with this change still.

You're right, but this is what other SDK still do, e.g. [here](https://github.com/getsentry/sentry-javascript/blob/f8aeeeab0006c9a0527fd8392bede8c534648325/packages/utils/src/dsn.ts#L50) and [here](https://github.com/getsentry/sentry-python/blob/b63b5ae32d254771cbd027009d0b6def7e2e07fb/sentry_sdk/utils.py#L188). I understand the concern that if you pass something that is not a number there will still be issues, but there are no public information that I'm aware of that the IDs will not be just digits also in the future

>returning a non-number as `int` could cause unexpected results

I wouldn't worry too much about the the cast in the getter because in the worst case the project ID will be `0`

Comment (stayallive) [reply src/Dsn.php:102]: Check the original issue. It's stated that it needs to be opaque, and UUID is mentioned explicitly too 😬

Comment (ste93cry) [reply src/Dsn.php:102]: Well, it's written that it could be an UUID or a 64bit number. I have no problems in removing this check, but since all other SDK seems to still require a number (stringified), I wonder if we should do it or not. @smeubank what do you suggest to do?

Comment (smeubank) [reply src/Dsn.php:102]: @HazAT can i get a PHP sanity check here, so to comply with the original request it needs to be UUID or 64 bit int?

**Review by stayallive — APPROVED** [review]
👍
